# fly.toml file generated for protohackers-in-elixir-sja on 2023-01-22T21:14:19+01:00

app = "protohackers-in-elixir-sja"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[experimental]
auto_rollback = true

[[services]]
# http_checks = []
internal_port = 5001
# processes = ["app"]
protocol = "tcp"
# script_checks = []

[[services.ports]]
handlers = []
port = 5001

[[services]]
internal_port = 5002
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5002

[[services]]
internal_port = 5003
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5003

[[services]]
internal_port = 5004
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5004

[[services]]
internal_port = 5005
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5005

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
