[package]
name = "protohackers_hellorust"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "protohackers_hellorust"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
